theme: minima
title: A physics blog
description: A place to discuss principles, problems, perspectives, practices, philosophy and pedagogy of physics
author: 
    name: Damitr
    email: "damitr@proton.me"
header_pages:
  - README.md
